version: '3.4'
services:
  myservice:
    networks:
      - mynetwork
  node-app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    command: npm run dev

    working_dir: /app

    environment:
      NODE_ENV: production


    volumes:
      - ./data:/app/data
