version: '3'
services:
  node-app:

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    working_dir: /app

    environment:
      NODE_ENV: production


    volumes:
      - ./data:/app/data
